#!/bin/sh

# Collect all arguments that are files
files=""
for arg in "$@"; do
    if [ -e "$arg" ]; then
        files="$files $(realpath $arg)"
    fi
done

# Construct bind arguments
bind_args=$(printf '%s\n' $files | xargs -I{} echo --ro-bind {} {})

# Run mpv with bubblewrap
bwrap --unsetenv \
  --unshare-all \
  --share-net \
  --die-with-parent \
  --proc /proc/ \
  --dev /dev/ \
  --dev-bind /dev/dri/ /dev/dri/ \
  --ro-bind /usr/ /usr/  \
  --ro-bind /bin/ /bin/ \
  --ro-bind /lib64/ /lib64/ \
  --ro-bind /run/ /run/ \
  --ro-bind /sys/ /sys/ \
  --ro-bind /etc/resolv.conf /etc/resolv.conf \
  --ro-bind /etc/fonts/ /etc/fonts/ \
  --ro-bind /etc/ssl/ /etc/ssl/ \
  --ro-bind /etc/ca-certificates/ /etc/ca-certificates/ \
  --ro-bind /etc/mpv/ /etc/mpv/ \
  --bind ~/.config/mpv/ ~/.config/mpv/ \
  --bind ~/.cache/mpv/ ~/.cache/mpv/ \
  --bind ~/.cache/mesa_shader_cache/ ~/.cache/mesa_shader_cache/ \
  $bind_args \
  mpv $@
